### ISSUE TITLE
Is this plugin working?

### ISSUE THREAD

**Issue by andys8** [kfkonrad/last-working-dir-fish-pkg#1]
I installed the plugin directly in `omf` and it looked fine. I tried to figure out how to use it, but looking at the source and the `README` I think this plugin is not ready at all. Or I don't know what it's intention is exactly.

A zsh implementation for comparison: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/last-working-dir/last-working-dir.plugin.zsh

**Comment by kfkonrad** [comment]
You're right, the plugin doesn't work properly. I wanted to tackle the bug and maybe just copy the zsh implementation for quite some time. Now that I know that someone is interested in my plugin (yeah 🎉) I should get it to work properly.

**Comment by andys8** [comment]
I'm happy to be your beta tester :)

**Comment by kfkonrad** [comment]
I think I fixed the issue with 45fddd5. You can use `omf update` to pull the latest version.

**Comment by andys8** [comment]
Whoa, looks good so far! I'll keep it installed and report if there would be any issues, but my first impression is good :+1: Thanks a lot.

**Comment by andys8** [comment]
Feedback: So the one issue I noticed, is probably expected (?) behavior. 

If I have two terminals open, one with VIM and another with a shell. Changing the directory will affect VIM. I think internally running commands in a new shell. Therefore when I use fuzzy search, it will search the directory of the other terminal, because it was changed. 
VIM config: https://github.com/avelino/vim-bootstrap/blob/master/vim_template/vimrc#L356-L372

Again, I think effects like this can be assumed. I'm still bringing it up, in case there is a way to avoid it, e.g. have a condition for https://github.com/kfkonrad/last-working-dir-fish-pkg/blob/c261b807b71c9da4c107a52dc3b9c6884069e4ff/init.fish#L8


The zsh code is [reading an environment variable `$ZSH_SUBSHELL`](https://github.com/robbyrussell/oh-my-zsh/blob/3d8f2bda599c8c6d160dc448e5ab28aaf2d5e90d/plugins/last-working-dir/last-working-dir.plugin.zsh#L7). I haven't found comparable information in `fish`, though.

**Comment by kfkonrad** [comment]
Yeah, that is expected behaviour.

I've read about issues with fish when it's being called by other scripts without shebang.
See eg. https://github.com/fish-shell/fish-shell/issues/4611. Just add `set SHELL=/bin/sh` to your `.vimrc` and vim won't even use fish.

If we keep getting this type of problem with more software, I'll think about adding a general solution (like only cd'ing into the last working dir in interactive shells).

**Comment by andys8** [comment]
Changing the shell can have other issues. Is there a way to recognize "interactive shells"? What are you thinking of?

**Comment by kfkonrad** [comment]
Scripts usually expect a POSIX-compatible shells, which fish isn't. Setting the shell shouldn't do any harm, quite the opposite, it can prevent syntax errors.

I found it: it's `status --is-interactive`. You may update `omf` again to test my fix using this command

**Comment by andys8** [comment]
There you go! :smiley: It looks like it fixed the issue.

Regarding shell: Yeah, probably my setup with `vim-bootstrap`. The [shell is set in the part ](https://github.com/avelino/vim-bootstrap/blob/b0a75e4d6440e97e3d332a41f653906a8beee5c9/vim_template/vimrc#L139-L143)which can't / shouldn't be changed. Changing the shell in `.vimrc.local` is probably to late. And I have a part of my environment only configured in fish (e.g. `asdf` and `sdkman`). Nevertheless, thanks again for the fix.
